## Data Audit - Credit Card Defaults ##

In [25]:
# importing useful packages
import pandas as pd
import numpy as np

In [29]:
# loading csv file
data = pd.read_csv("Default_of_Credit_Card_Clients.csv", header=1, index_col=0)

In [30]:
# inspecting data file
print(data.head(5))

    LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
ID                                                                         
1       20000    2          2         1   24      2      2     -1     -1   
2      120000    2          2         2   26     -1      2      0      0   
3       90000    2          2         2   34      0      0      0      0   
4       50000    2          2         1   37      0      0      0      0   
5       50000    1          2         1   57     -1      0     -1      0   

    PAY_5             ...              BILL_AMT4  BILL_AMT5  BILL_AMT6  \
ID                    ...                                                
1      -2             ...                      0          0          0   
2       0             ...                   3272       3455       3261   
3       0             ...                  14331      14948      15549   
4       0             ...                  28314      28959      29547   
5       0             .

In [31]:
# identifying unique values in each column
print(data.SEX.unique())
print(data.EDUCATION.unique())
print(data.MARRIAGE.unique())
print(data.PAY_0.unique())

[2 1]
[2 1 3 5 4 6 0]
[1 2 3 0]
[ 2 -1  0 -2  1  3  4  8  7  5  6]


#### Code Block Above Explaination ##

The purpose of the block above is to identify if there are values that are included in columns that were not mentioned in the [Data Dictionary](ba545-data/Competition2-My-Files/Data_Dictionary.md). The data dictionary that was given from the link to the website mentions for missing values is 'N/A', so there can be a combination of empty records, as well as other values, such as 0, that represent missing values.

In [32]:
### USING THIS CODE FROM COMPETITION 1

# Creating an empty list for column names
names = []

# Creating an empty list for the number of null values in each column
values = []

# Checking for Missing Values
for col in data.columns:
    names.append(col)
    values.append(data[col].isnull().sum())
    print(names[-1],values[-1])

LIMIT_BAL 0
SEX 0
EDUCATION 0
MARRIAGE 0
AGE 0
PAY_0 0
PAY_2 0
PAY_3 0
PAY_4 0
PAY_5 0
PAY_6 0
BILL_AMT1 0
BILL_AMT2 0
BILL_AMT3 0
BILL_AMT4 0
BILL_AMT5 0
BILL_AMT6 0
PAY_AMT1 0
PAY_AMT2 0
PAY_AMT3 0
PAY_AMT4 0
PAY_AMT5 0
PAY_AMT6 0
default payment next month 0


__So if we just went by this, we are thinking that there are no missing values. Reading through the [Data Dictionary](ba545-data/Competition2-My-Files/Data_Dictionary.md), the number `0` is never used for any values. `0` shows up in columns throughout the data set, so we can assume that the missing values are categorized as the number `0`.__

In [36]:
# re-loading the csv file with missing values coded
data = pd.read_csv("Default_of_Credit_Card_Clients.csv", header=1, index_col=0, na_values=0)

In [37]:
# inspecting the data with missing values
print(data.head(3))

    LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
ID                                                                         
1       20000    2        2.0       1.0   24    2.0    2.0   -1.0   -1.0   
2      120000    2        2.0       2.0   26   -1.0    2.0    NaN    NaN   
3       90000    2        2.0       2.0   34    NaN    NaN    NaN    NaN   

    PAY_5             ...              BILL_AMT4  BILL_AMT5  BILL_AMT6  \
ID                    ...                                                
1    -2.0             ...                    NaN        NaN        NaN   
2     NaN             ...                 3272.0     3455.0     3261.0   
3     NaN             ...                14331.0    14948.0    15549.0   

    PAY_AMT1  PAY_AMT2  PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  \
ID                                                               
1        NaN     689.0       NaN       NaN       NaN       NaN   
2        NaN    1000.0    1000.0    1000.0       N

In [38]:
# identifying unique values in each column with missing values coded
print(data.SEX.unique())
print(data.EDUCATION.unique())
print(data.MARRIAGE.unique())
print(data.PAY_0.unique())

[2 1]
[ 2.  1.  3.  5.  4.  6. nan]
[ 1.  2.  3. nan]
[ 2. -1. nan -2.  1.  3.  4.  8.  7.  5.  6.]


In [39]:
# Creating an empty list for column names
names = []

# Creating an empty list for the number of null values in each column
values = []

# Checking for Missing Values
for col in data.columns:
    names.append(col)
    values.append(data[col].isnull().sum())
    print(names[-1],values[-1])

LIMIT_BAL 0
SEX 0
EDUCATION 14
MARRIAGE 54
AGE 0
PAY_0 14737
PAY_2 15730
PAY_3 15764
PAY_4 16455
PAY_5 16947
PAY_6 16286
BILL_AMT1 2008
BILL_AMT2 2506
BILL_AMT3 2870
BILL_AMT4 3195
BILL_AMT5 3506
BILL_AMT6 4020
PAY_AMT1 5249
PAY_AMT2 5396
PAY_AMT3 5968
PAY_AMT4 6408
PAY_AMT5 6703
PAY_AMT6 7173
default payment next month 23364


# __DO NOT IMPUTE 'DEFAULT PAYMENT NEXT MONTH!__ #

__Now there are a lot more missing values. Rarely there will be a data set with no missing values.__

What we will have to do for descriptive statistics is to impute for these missing data values so we have no missing values. The total amount of records is `30,000`.