### Data Audit - Credit Card Defaults ###

In [1]:
# importing packages
import pandas as pd
import numpy as np

In [11]:
# loading in excel file

data = pd.read_excel("default of credit card clients.xls", header=1, index_col=0)

In [12]:
print(data.head(5))

    LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
ID                                                                         
1       20000    2          2         1   24      2      2     -1     -1   
2      120000    2          2         2   26     -1      2      0      0   
3       90000    2          2         2   34      0      0      0      0   
4       50000    2          2         1   37      0      0      0      0   
5       50000    1          2         1   57     -1      0     -1      0   

    PAY_5             ...              BILL_AMT4  BILL_AMT5  BILL_AMT6  \
ID                    ...                                                
1      -2             ...                      0          0          0   
2       0             ...                   3272       3455       3261   
3       0             ...                  14331      14948      15549   
4       0             ...                  28314      28959      29547   
5       0             .

In [23]:
# identifying unique values in each column
print(data.SEX.unique())
print(data.EDUCATION.unique())
print(data.MARRIAGE.unique())
print(data.PAY_0.unique())

[2 1]
[2 1 3 5 4 6 0]
[1 2 3 0]
[ 2 -1  0 -2  1  3  4  8  7  5  6]


In [25]:
# changing the last column name
data.rename(columns = {'default payment next month':'default_pay_next_month'});

In [27]:
# exporting data to new dataframe cause who the hell puts spaces in a column name
data.to_csv("Default_of_Credit_Card_Clients.csv", ",")